### ISSUE TITLE
Cannot build when targeting `/cjs` with Node 14

### ISSUE THREAD

**Issue by isaachinman** [i18next/i18next-fs-backend#1]
When importing `i18next-fs-backend/cjs` in Node 14, the following error occurs:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cjs' is not defined by "exports" in /next-i18next/examples/simple/node_modules/i18next-fs-backend/package.json
    at applyExports (internal/modules/cjs/loader.js:492:9)
    at resolveExports (internal/modules/cjs/loader.js:508:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (eval at _default (/next-i18next/examples/simple/.next/server/static/7wWeh8OP0ULywbDqIKGvK/pages/_app.js:10252:30), <anonymous>:1:1)
    at _default (/next-i18next/examples/simple/.next/server/static/7wWeh8OP0ULywbDqIKGvK/pages/_app.js:10252:30)
    at new NextI18Next (/next-i18next/examples/simple/.next/server/static/7wWeh8OP0ULywbDqIKGvK/pages/_app.js:9923:66) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by adrai** [comment]
or here...
If we fix, one we fix both ;-)

**Comment by adrai** [comment]
i18next-fs-backend@1.0.2
