### ISSUE TITLE
Cannot build on Vercel.com

### ISSUE THREAD

**Issue by FMCorz** [i18next/i18next-fs-backend#4]
Sorry, I posted this by accident, here is the full report.

The error is:

```
> Built @now/node@canary:index.ts [4s]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/cjs/index.js
require() of ES modules is not supported.
require() of /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/cjs/index.js from /tmp/zeit-fun-78fd5854bff96/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:13)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/code/js/project/index.ts:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14) {
  code: 'ERR_REQUIRE_ESM'
}
LambdaError: RequestId: 80011882-8756-4c7f-a7dd-fd826b996ff7 Process exited before completing request
    at Lambda.<anonymous> (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:3456053)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:3453940)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/cjs/index.js
require() of ES modules is not supported.
require() of /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/cjs/index.js from /tmp/zeit-fun-78fd5854bff96/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/zeit-fun-78fd5854bff96/node_modules/i18next-fs-backend/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:13)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/user/code/js/project/index.ts:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14) {
  code: 'ERR_REQUIRE_ESM'
}
LambdaError: RequestId: b909ac67-b5be-46e5-b3b4-8b904cd4f7ae Process exited before completing request
    at Lambda.<anonymous> (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:3456053)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/.config/yarn/global/node_modules/now/dist/index.js:2:3453940)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Not too sure how to fix this. This also happens with the `i18n-http-middleware` plugin.

**Comment by adrai** [comment]
You need to import with /cjs at the end
i.e. i18next-http-middleware/cjs

reason is somewhere here: https://github.com/isaachinman/next-i18next/issues/274#issuecomment-622948743

**Comment by FMCorz** [comment]
I see, sorry for the noise!

**Comment by adrai** [comment]
I just wished Vercel would fix it and respect the node.js standards 🤷‍♂️

**Comment by FMCorz** [comment]
I've had my share of issues with them lately, would you recommend another similar service?

**Comment by adrai** [comment]
Can’t recommend any other, beside an own lambda function behind an API-GW.

**Comment by adrai** [comment]
fyi: With the latest version importing with `/cjs` should not be necessary anymore.
