### ISSUE TITLE
cjs mediaType unknown

### ISSUE THREAD

**Issue by vrumjantsev** [i18next/i18next-fs-backend#5]
Getting an error while initializing 

`i18next.use(Backend).init({
    initImmediate: false,
    fallbackLng  : 'en',
    backend      : {
        loadPath: 'translations/{{lng}}/{{ns}}.json',
    }
});`

`error: Uncaught TypeError: Cannot resolve extension for "https://deno.land/x/i18next_fs_backend/lib/fs.cjs" with mediaType "Unknown".
    at getExtension ($deno$/compiler.ts:186:13)
    at new SourceFile ($deno$/compiler.ts:219:22)
    at Function.addToCache ($deno$/compiler.ts:226:16)
    at buildSourceFileCache ($deno$/compiler.ts:588:16)
    at compile ($deno$/compiler.ts:1147:3)
    at tsCompilerOnMessage ($deno$/compiler.ts:1338:22)
    at workerMessageRecvCallback ($deno$/runtime_worker.ts:72:33)
`
deno 1.0.2
v8 8.4.300
typescript 3.9.2
https://deno.land/x/i18next@v19.4.5/index.js
https://deno.land/x/i18next_fs_backend@v1.0.3/index.js

**Comment by adrai** [comment]
strange... worked with v1.0.0

**Comment by adrai** [comment]
@vrumjantsev opened an issue here: https://github.com/denoland/deno/issues/5878 any help is welcome

**Comment by adrai** [comment]
Should work again with deno v1.0.4
