### ISSUE TITLE
TypeError: fs.readFile is not a function

### ISSUE THREAD

**Issue by mrceperka** [i18next/i18next-fs-backend#6]
Hello,

having hard time to set i18n with razzle.

Node version: 12.16.1
Razzle: 3.0

```
  TypeError: fs.readFile is not a function
      at /var/bb/packages/frontend/var/bb/node_modules/i18next-fs-backend/lib/readFile.js:15:1
      at new Promise (<anonymous>)
      at readFileInNode (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/lib/readFile.js:15:1)
      at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/lib/readFile.js:90:1
      at new Promise (<anonymous>)
      at readFile (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/lib/readFile.js:89:1)
      at Backend.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/lib/index.js:48:1)
      at Connector.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1626:1)
      at Connector.loadOne (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1692:1)
      at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1665:1,
```

This hack fixes it, but I don't like it :D

```js
Backend.prototype.read = function (language, namespace, callback) {
  let filename = this.services.interpolator.interpolate(this.options.loadPath, {
    lng: language,
    ns: namespace,
  });

  fs.readFile(filename, (err, resources) => {
    if (err) return callback(err, false);
    callback(null, JSON.parse(resources.toString()));
  });
};
```
What's wrong with fs in this package? Is it possible that HMR breaks it? Any ideas what I am doing wrong? 

Thanks :pray:

**Comment by adrai** [comment]
Can you provide an example?

**Comment by adrai** [comment]
Alternatively, try importing ‘i18next-fs-backend/cjs’

**Comment by mrceperka** [comment]
importing ‘i18next-fs-backend/cjs’ fixed the error, but my translations are empty :/

**Comment by adrai** [comment]
try to set debug to true and check the logs

**Comment by mrceperka** [comment]
I've set debug to true, this is output.

```
✅  Server-side HMR Enabled!
res-err TypeError: fs.readFile is not a function
    at /var/bb/packages/frontend/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:36:1
    at new Promise (<anonymous>)
    at readFileInNode (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:35:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:132:1
    at new Promise (<anonymous>)
    at readFile (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:131:1)
    at Backend.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/index.js:80:1)
    at Connector.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1626:1)
    at Connector.loadOne (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1692:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1665:1
i18next::backendConnector: loading namespace translation for language en failed TypeError: fs.readFile is not a function
    at /var/bb/packages/frontend/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:36:1
    at new Promise (<anonymous>)
    at readFileInNode (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:35:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:132:1
    at new Promise (<anonymous>)
    at readFile (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:131:1)
    at Backend.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/index.js:80:1)
    at Connector.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1626:1)
    at Connector.loadOne (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1692:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1665:1
res-err TypeError: fs.readFile is not a function
    at /var/bb/packages/frontend/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:36:1
    at new Promise (<anonymous>)
    at readFileInNode (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:35:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:132:1
    at new Promise (<anonymous>)
    at readFile (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:131:1)
    at Backend.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/index.js:80:1)
    at Connector.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1626:1)
    at Connector.loadOne (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1692:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1665:1
i18next::backendConnector: loading namespace translation for language cs failed TypeError: fs.readFile is not a function
    at /var/bb/packages/frontend/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:36:1
    at new Promise (<anonymous>)
    at readFileInNode (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:35:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:132:1
    at new Promise (<anonymous>)
    at readFile (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/readFile.js:131:1)
    at Backend.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next-fs-backend/cjs/index.js:80:1)
    at Connector.read (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1626:1)
    at Connector.loadOne (/var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1692:1)
    at /var/bb/packages/frontend/build/webpack:/var/bb/node_modules/i18next/dist/esm/i18next.js:1665:1
i18next: languageChanged en
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: 'translation',
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  whitelist: [ 'en', 'cs', 'cimode' ],
  nonExplicitWhitelist: false,
  load: 'all',
  preload: [ 'en', 'cs' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  postProcessPassResolved: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation: { formatSeparator: ',', format: [Function: format] },
  lng: 'en',
  react: { useSuspense: false, wait: true },
  backend: {
    loadPath: '/var/bb/packages/frontend/src/locales/{{lng}}/{{ns}}.json',
    addPath: '/var/bb/packages/frontend/src/locales/{{lng}}/{{ns}}.missing.json',
    ident: 2,
    parse: [Function: parse],
    stringify: [Function: stringify]
  }
}
i18next: languageChanged en
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'translation' ],
  defaultNS: 'translation',
  fallbackLng: [ 'en' ],
  fallbackNS: false,
  whitelist: [ 'en', 'cs', 'cimode' ],
  nonExplicitWhitelist: false,
  load: 'all',
  preload: [ 'en', 'cs' ],
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  postProcessPassResolved: false,
  returnNull: true,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation: { formatSeparator: ',', format: [Function: format] },
  lng: 'en',
  react: { useSuspense: false, wait: true },
  backend: {
    loadPath: '/var/bb/packages/frontend/src/locales/{{lng}}/{{ns}}.json',
    addPath: '/var/bb/packages/frontend/src/locales/{{lng}}/{{ns}}.missing.json',
    ident: 2,
    parse: [Function: parse],
    stringify: [Function: stringify]
  }
}
```

**Comment by adrai** [comment]
Can you share some repo that reproduces this?

**Comment by mrceperka** [comment]
Well repo is private but I will try to make an example repo where this bug occurs.

**Comment by adrai** [comment]
I tried with: https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr
but could not reproduce it.

**Comment by mrceperka** [comment]
There you go
https://github.com/mrceperka/i18next-fs-backend-error

**Comment by adrai** [comment]
I just, npm i
and npm start...
seems to work...
did not test docker stuff

**Comment by mrceperka** [comment]
wtf... might be related to alpine node image....

**Comment by adrai** [comment]
does this work for you without docker stuff?

**Comment by mrceperka** [comment]
Will try...

**Comment by mrceperka** [comment]
Work, damn! I will try another docker image...

**Comment by adrai** [comment]
I just tested with docker stuff... as described in your README.md and it works too...
so this must be a local issue on your side?
Can this be closed?

**Comment by mrceperka** [comment]
Well, works with node:12 docker image. Looks like alpine issue...

**Comment by mrceperka** [comment]
What? :D really? Damn

Sure close it, thanks for debug.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
There are many ways to help this project 🙏

**Comment by mrceperka** [comment]
Sorry to bother you again, but I've observed some strange behavior.

If I change source code of `lib/readFile.js` and modify `readFileInNode` function to this:
```js
const readFileInNode = (filename) => {
  console.log('readFileInNode - fs', fs)
  console.log('readFileInNode - fsMod', fsMod)
  return new Promise((resolve, reject) => fs.readFile(filename, 'utf8', (err, data) => err ? reject(err) : resolve(data)))
}
```

I got following console logs, which are very weird...
```
readFileInNode - fs http://localhost:3001/static/media/fs.2e34f627.cjs
readFileInNode - fsMod http://localhost:3001/static/media/fs.2e34f627.cjs
```

Why the heck is fs and fsMod string? :D

If i change 
```js
const fs = fsMod ? (fsMod.default || fsMod) : undefined // because of strange export
```
to
```js
import * as fs from 'fs' 
```

Everything works...

It looks like code in `lib/fs.cjs` file is not even executed.

**Comment by adrai** [comment]
The fs import has to be done like this to be compatible with Node.js (ESM and CommonJs) and Deno...

filename like "http://localhost:3001/static/media/fs.2e34f627.cjs" looks really strange, as you would use some compiled stuff...

I have no such issues... why are you changing the code? Do you have another issue now? If so, create a reproducable example and create a new issue.

**Comment by mrceperka** [comment]
I've just added some logs, that's all. I can't create reproducible example. The one that I've created works...

I've hoped that you might have some idea. But nevermind.

Thanks again anyway.

**Comment by AlexMayants** [comment]
@mrceperka, I've just encountered the same problem. In my case, the server application is a React universal app built with Webpack. Webpack has some loaders for different file types like `url-loader` for images, `css-loader` for styles etc., with exceptions from othere rules being handled by `file-loader`. I solved the problem by excluding `*.cjs` files from `file-loader` processing. The overall fix diff is like this:

```diff
@@ -160,21 +160,21 @@ const CONFIG_SERVER = {
   module: {
     rules: [
       {
         exclude: [
           /\.html?$/,
-          /\.(js|jsx)$/,
+          /\.(js|jsx|cjs)$/,
           /\.s?css$/,
           ...
         ],
         loader: require.resolve('file-loader')
       },
@@ -187,21 +187,21 @@ const CONFIG_SERVER = {
       {
-        test: /\.(js|jsx)$/,
+        test: /\.(js|jsx|cjs)$/,
         include: paths.appSrc,
         exclude: paths.serverIndexJs,
         use: [
           'babel-loader',
           'eslint-loader'
         ]
       },
```

`i18next-fs-backend` uses a wrapper for node's `fs` in a file named `fs.cjs`. The issue was caused by Webpack trying to import `*.cjs` files as text.

Hope this helps!

**Comment by mrceperka** [comment]
@AlexMayants thank you for you idean and solution, it could probably solve the issue. I will try to implement it. Not sure how to do it with razzle, but I will figure something out :D

(For now I am using deprecated https://github.com/i18next/i18next-node-fs-backend which works fine)

**Comment by adrai** [comment]
The razzle example in the react-i18next seems to work.

On 5 Jun 2020, at 13:54, Mr Ceperka <notifications@github.com> wrote:

﻿

@AlexMayants<https://github.com/AlexMayants> thank you for you idea and solution, it could probably solve the issue. I will try to implement it. Not sure how to do it with razzle, but I will figure something out :D

(For now I am using deprecated https://github.com/i18next/i18next-node-fs-backend which works fine)

**Comment by mrceperka** [comment]
@adrai Could we just rename that `lib/fs.cjs` to `lib/fs.js`? It works with this rename without any razzle config modifications.

(btw i18next razzle example does work for me. maybe my build is broken beacause of ts. dunno)

**Comment by adrai** [comment]
@mrceperka I can do this only for the cjs dist... Can you try with v1.0.5 ?

**Comment by mrceperka** [comment]
Will try asap. thanks.

**Comment by mrceperka** [comment]
:tada: Aaaaand it works!
```ts
// @ts-ignore
import Backend from "i18next-fs-backend/cjs";
```
@adrai Thanks for fast response & fix! :pray:

**Comment by adrai** [comment]
fyi: With the latest version importing with `/cjs` should not be necessary anymore.

**Comment by NiloDrumond** [comment]
Hi!

I'm having the same problem with react.

``i18next::backendConnector: loading namespace backend-app for language en failed TypeError: fs.readFileSync is not a function``

https://gist.github.com/NiloDrumond/92ff755e77e57a6ed2e9d0dc591c96c3

Here is my i18n config file:

```import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-fs-backend';

i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
    debug: true,
    initImmediate: false,
    fallbackLng: 'en',
    lng: 'en',
    preload: ['en'],
    ns: 'backend-app',
    defaultNS: 'backend-app',
    backend: {
      loadPath:
        process.env.NODE_ENV !== 'production'
          ? `./locales/{{lng}}/{{ns}}.json`
          : ` ./app/locales/{{lng}}/{{ns}}.json`,
    },
    react: {
      useSuspense: false, // https://stackoverflow.com/questions/59464880/how-to-fix-no-fallback-ui-was-specified-in-react-i18next-using-hooks
    },
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;
```

In another project, I use i18next-http-backend with no problem, but as in this project I'm using electron, I choose to use fs instead, but I still haven't managed to make it work.

Thanks!

**Comment by guptaashwanee** [comment]
```import Backend from "i18next-fs-backend```
