### ISSUE TITLE
YAML - Cannot read property 'safeLoad' of undefined

### ISSUE THREAD

**Issue by schwarmco** [i18next/i18next-fs-backend#7]
## 🐛 Bug Report

In NodeJS-Environment, `YAML` is undefined in `readFile.js`, resulting in the error:

```
i18next::backendConnector: loading namespace test for language dev failed TypeError: error parsing /home/js/i18next-bug/test.yml: Cannot read property 'safeLoad' of undefined
    at parseData (/home/js/i18next-bug/node_modules/i18next-fs-backend/cjs/readFile.js:86:21)
    at /home/js/i18next-bug/node_modules/i18next-fs-backend/cjs/readFile.js:134:19
```

## To Reproduce

```js
const i18next = require('i18next')
const Backend = require('i18next-fs-backend')
const path = require('path')

i18next.use(Backend).init({
    debug: true,
    ns: "test",
    backend: {
        loadPath: path.join(__dirname, '{{ns}}.yml')
    }
}, err => console.error)
```

## Your Environment

- *runtime version*: Node v12.16.3 (lts)
- *i18next version*:19.4.5
- *i18next-fs-backend version*:1.0.4
- *os*: Debian Linux (also fails in `node:lts` Docker)

**Comment by adrai** [comment]
I'm not able to reproduce it...
There are also tests here: https://github.com/i18next/i18next-fs-backend/blob/master/test/backend.yaml.js
and I locally modified the example here: https://github.com/i18next/i18next-fs-backend/blob/master/example/node/index.js to read yml files...

**Comment by schwarmco** [comment]
I've digged a little into it and found the issue only in cjs - that's why the tests are working.

Here's a Docker-Image to reproduce the error:

```docker
FROM node:lts

WORKDIR /app

RUN npm i i18next

RUN git clone https://github.com/i18next/i18next-fs-backend
RUN cd i18next-fs-backend && npm install && npm run build

# Replace JSON with YAML in Example
RUN sed -i "s/loadPath.*/loadPath\: 'locales\/{{lng}}\/{{ns}}.yml'/" i18next-fs-backend/example/node/index.js

# Create YAML Translations
RUN echo "welcome: hello world" > i18next-fs-backend/example/node/locales/en/translation.yml
RUN echo "welcome: hallo welt" > i18next-fs-backend/example/node/locales/de/translation.yml

# Change Workdir to Example
WORKDIR /app/i18next-fs-backend/example/node

# Run Example
CMD ["node", "index.js"]
```

Which outputs:

```bash
$ docker build --tag i18next-fs-backend-gh-7 .                                                                    
Sending build context to Docker daemon  47.77MB
....
Successfully tagged i18next-fs-backend-gh-7:latest

$ docker run -it --rm i18next-fs-backend-gh-7                                                                     
welcome
welcome
[
  TypeError: error parsing locales/en/translation.yml: Cannot read property 'safeLoad' of undefined
      at parseData (/app/i18next-fs-backend/cjs/readFile.js:86:21)
      at /app/i18next-fs-backend/cjs/readFile.js:134:19,
  TypeError: error parsing locales/de/translation.yml: Cannot read property 'safeLoad' of undefined
      at parseData (/app/i18next-fs-backend/cjs/readFile.js:86:21)
      at /app/i18next-fs-backend/cjs/readFile.js:134:19
]
```

I've also tested with `node:14`, which results in the same error.

I also rewrote the `test/backend.yaml.js` to use cjs:

```
const expect = require('expect.js')
const dirname = require('path').dirname
const fileURLToPath = require('url').fileURLToPath
const i18next = require('i18next')
const writeFile = require('../cjs/writeFile.js').writeFile
const Backend = require('../cjs/index.js')

i18next.init()

describe('BackendConnector with yaml', () => {
  let connector

  before((done) => {
    connector = i18next.services.backendConnector
    connector.backend = new Backend(i18next.services, {
      loadPath: `${__dirname}/locales/{{lng}}/{{ns}}.yaml`,
      addPath: `${__dirname}/locales/{{lng}}/{{ns}}.yaml`
    })
    writeFile(`${__dirname}/locales/en/test.yaml`, { key: 'passing' }).then(done).catch(done)
  })

  after((done) => {
    writeFile(`${__dirname}/locales/en/test.yaml`, { key: 'passing' }).then(done).catch(done)
  })

  describe('#load', () => {
    it('should load data', (done) => {
      connector.load(['en'], ['test'], (err) => {
        expect(err).not.to.be.ok()
        expect(connector.store.getResourceBundle('en', 'test')).to.eql({
          key: 'passing'
        })
        done()
      })
    })
  })

  describe('#saveMissing', () => {
    it('should load data', (done) => {
      connector.backend.create(['en'], 'test', 'newKey', 'fallback', (err) => {
        expect(err).not.to.be.ok()
        connector.backend.read(['en'], ['test'], (err, ns) => {
          expect(err).not.to.be.ok()
          expect(ns).to.eql({
            key: 'passing',
            newKey: 'fallback'
          })
        })
      })
    })
  })
})
```

Which then fails:

```bash
$ npx mocha test/backend.yaml.cjs


  BackendConnector with yaml
    1) "before all" hook in "BackendConnector with yaml"
    2) "after all" hook in "BackendConnector with yaml"


  0 passing (5ms)
  2 failing

  1) BackendConnector with yaml
       "before all" hook in "BackendConnector with yaml":
     TypeError: error stringifying /home/js/i18next-fs-backend/test/locales/en/test.yaml: Cannot read property 'safeDump' of undefined
      at stringifyData (cjs/writeFile.js:76:21)
      at writeFile (cjs/writeFile.js:115:12)
      at Context.<anonymous> (test/backend.yaml.cjs:19:5)
      at processImmediate (internal/timers.js:456:21)

  2) BackendConnector with yaml
       "after all" hook in "BackendConnector with yaml":
     TypeError: error stringifying /home/js/i18next-fs-backend/test/locales/en/test.yaml: Cannot read property 'safeDump' of undefined
      at stringifyData (cjs/writeFile.js:76:21)
      at writeFile (cjs/writeFile.js:115:12)
      at Context.<anonymous> (test/backend.yaml.cjs:23:5)
      at processImmediate (internal/timers.js:456:21)
```

due to YAML being undefined

**Comment by adrai** [comment]
Outside of the docker it works 🤷‍♂️

**Comment by schwarmco** [comment]
not on my machine(s):
* Server with Ubuntu 18.04.4 LTS & Node v12.13.0
* Desktop with Debian 10 & Node 14.1.0

and Docker Images
* node:14
* node:14-buster 
* node:14-alpine

all failing the above cjs test - i guess these are very common environments for running Node

**Comment by adrai** [comment]
strange... i tested with node 14 and node 12...
nevertheless, will add that `typeof YAMLDummy !== 'undefined' ? YAMLDummy` check...

**Comment by adrai** [comment]
v1.0.6 should fix this
